# **WEEK 1 - FOUNDATIONS: CLEANING & EXPLORING THE APPLICANT DATASET**

## **Step 1: Setting Up My Environment**

Setting Up My Environment
1. I created a new notebook by clicking File -> New -> Notebook.
2. I renamed the notebook by clicking File -> Rename and then changed its name to Week1_Data_Cleaning_Billium.
3. I imported the required library #pandas
4. I created a markdown cell above it by pressing Esc and A simultaneously.

In [106]:
import pandas as pd

## **Step 2: Create applicants.csv**

In [110]:
from faker import Faker
import pandas as pd
import random

fake = Faker()

applicants = []

universities = [
    "University of Nairobi",
    "Kenyatta University",
    "Moi University",
    "Egerton University",
    "JKUAT University",
    "Maseno University",
    ""
]

statuses = ["Under Review", "Selected", "Rejected", "SELECTED", "selected", "UNDER REVIEW", ""]
domain = ["web dev", "Web development", "webdev", "WEB DEV", "web development",
          " web development ", "Applied Statistics", "APPLIED Statistics", "Data SCIENCE", "COMPUTER sci", "PURE MATHEMATICS"]
date = ["13/05/2026", "2026-05-12"]

for i in range(100):
    applicants.append({
        #Applicants with missing applicant names
        "Applicant_Name":(
            None if i >= 5 and i < 8 #Created missing values between line number index 5 and line index 8 excluding the line index 8 .
            else fake.name()
        ),
        #Applicants with missing emails
        "Email" : (
            None if i >= 98 #Created two missing values
            else fake.email()
            
        ),
        "Phone": fake.phone_number(),
        "Domain_Applied":random.choice(domain),
        "University_Name": (
            None if i == 21 #Creating a missing value in line index 21
            else random.choice(universities)
        ),
        "Application_date": random.choice(date),
        "Status": random.choice(statuses)
        
    })

df = pd.DataFrame(applicants)

df.to_csv("applicants.csv", index=False)

#If you have many rows, pandas may hide some of them. To display everything, use:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Duplicate the first three rows
df = pd.concat([df, df.iloc[:3]], ignore_index=True)

df

,Applicant_Name,Email,Phone,Domain_Applied,University_Name,Application_date,Status
0,Valerie Miller,melanie29@example.org,809-313-8551x7574,webdev,,2026-05-12,Under Review
1,Robert Johnston,briansmith@example.org,568.788.3065x7244,Web development,Moi University,2026-05-12,
2,Breanna Solis,christopher86@example.net,001-812-435-4182x708,web dev,Egerton University,13/05/2026,SELECTED
3,Dawn Kim,kristen00@example.com,976.444.1756x4317,webdev,Egerton University,2026-05-12,UNDER REVIEW
4,Derrick Moore,kolson@example.net,5909238996,COMPUTER sci,Maseno University,2026-05-12,Selected
5,NaN,hooperjasmine@example.net,704-635-5971x34532,Web development,JKUAT University,13/05/2026,UNDER REVIEW
6,NaN,meyerfrank@example.com,(502)934-5128,webdev,,13/05/2026,Under Review
7,NaN,jonathanmills@example.org,545.701.2817x856,PURE MATHEMATICS,Moi University,13/05/2026,Under Review
8,Jose Wells,donnaobrien@example.org,8907345073,web development,,2026-05-12,
9,Lucas Odonnell,fishermichael@example.org,378-625-0726,web development,Moi University,13/05/2026,Rejected
10,Ian Hoffman,atran@example.com,9598907482,PURE MATHEMATICS,University of Nairobi,2026-05-12,Under Review
11,Mary Lee,amyharvey@example.org,913-350-7350,WEB DEV,JKUAT University,2026-05-12,selected
12,Jamie Andrews,myersjohn@example.net,990.608.2287x5855,WEB DEV,,13/05/2026,Selected
13,Benjamin Villa,cassandra07@example.com,001-756-364-2724x3188,PURE MATHEMATICS,Kenyatta University,2026-05-12,Selected
14,Ashley Mora,stanleyashley@example.com,212.526.8342x12423,web development,JKUAT University,2026-05-12,selected
15,Susan Patel,jhunt@example.org,001-545-483-9515x09972,webdev,JKUAT University,2026-05-12,selected
16,Melissa Hall,jameshobbs@example.org,+1-750-690-8509x55260,web development,,13/05/2026,UNDER REVIEW
17,Jacob Banks,nbell@example.com,(895)393-2376x88308,Applied Statistics,,2026-05-12,Under Review
18,Brandon Cox,xschmidt@example.com,8806548810,web development,Kenyatta University,13/05/2026,Selected
19,Carolyn Wilson,sandragallegos@example.com,(481)608-8078x6328,web development,University of Nairobi,13/05/2026,Under Review
20,Edward Taylor,shawnmunoz@example.org,9763205299,WEB DEV,Egerton University,2026-05-12,selected
21,Rick Wiggins,ginareed@example.net,+1-989-452-8844x510,COMPUTER sci,NaN,13/05/2026,Rejected
22,Sandra Flores,fcarroll@example.com,+1-819-407-4519x86541,web dev,JKUAT University,13/05/2026,SELECTED
23,Patricia Graves,russellrichard@example.org,(834)276-0411x0843,Data SCIENCE,,13/05/2026,Rejected
24,Timothy Smith,kcarpenter@example.org,7882160493,PURE MATHEMATICS,Egerton University,2026-05-12,
25,Alicia Austin,mitchellelizabeth@example.net,816-737-9623,APPLIED Statistics,University of Nairobi,13/05/2026,
26,David Ramirez,randall53@example.com,820-711-6963,Web development,Egerton University,13/05/2026,UNDER REVIEW
27,Larry Walker,amandasimmons@example.net,835.620.2605x0890,WEB DEV,Egerton University,2026-05-12,Selected
28,Cameron Harris,bartondaniel@example.net,+1-339-424-0646x5396,Data SCIENCE,Egerton University,2026-05-12,UNDER REVIEW
29,Edward Bowen,laurenhernandez@example.org,434-823-5377,PURE MATHEMATICS,Egerton University,13/05/2026,UNDER REVIEW
30,Jean Stephens,jason32@example.org,908-328-2783,webdev,University of Nairobi,13/05/2026,Selected
31,Stephanie Petersen,yaustin@example.net,001-247-594-8316,web dev,Kenyatta University,2026-05-12,Under Review
32,Michael Lopez,allisonwest@example.net,(976)376-6543,COMPUTER sci,University of Nairobi,2026-05-12,Rejected
33,Teresa Garcia,zrodriguez@example.org,968.623.2869x93308,WEB DEV,Egerton University,2026-05-12,Selected
34,Regina Orozco,thomas38@example.net,001-660-227-2537x182,Web development,JKUAT University,13/05/2026,SELECTED
35,Ryan Thompson,dana88@example.org,001-368-642-5345x32683,web dev,Moi University,2026-05-12,Rejected
36,Jennifer Adkins,creid@example.org,(222)613-9833,COMPUTER sci,University of Nairobi,2026-05-12,selected
37,Mr. Brian Schaefer,jonessamantha@example.net,967-591-6996,APPLIED Statistics,,2026-05-12,UNDER REVIEW
38,Clifford Rasmussen,martinezjoshua@example.net,(836)280-7639x00121,web dev,Kenyatta University,2026-05-12,Under Review
39,Patrick Mcdonald,ksantos@example.org,+1-845-579-7771,web development,JKUAT University,13/05/2026,SELECTED
40,Veronica Smith,anthonylee@example.org,(696)605-1853,Applied Statistics,,2026-05-12,Selected
41,Jessica Perez,kelly21@example.com,264-476-7258x260,WEB DEV,University of Nairobi,2026-05-12,SELECTED
42,Jessica Dodson,jonathanmaddox@example.com,998-213-0656,APPLIED Statistics,Kenyatta University,13/05/2026,Selected
43,Judith Knapp,troyshelton@example.org,6896680768,APPLIED Statistics,,2026-05-12,Under Review
44,Lauren Blackburn,melissaford@example.com,792-213-6716x4655,Applied Statistics,Maseno University,2026-05-12,selected
45,George Hall,lpalmer@example.org,763.856.8937,COMPUTER sci,University of Nairobi,2026-05-12,Selected
46,Dustin Rodriguez,jamie17@example.net,+1-244-692-2780,webdev,Moi University,13/05/2026,selected
47,Kathleen Doyle,daniel20@example.com,+1-919-526-8291x8264,webdev,,13/05/2026,SELECTED
48,Stephanie Webster,hroberts@example.com,(411)431-2867x9531,APPLIED Statistics,Kenyatta University,2026-05-12,SELECTED
49,Jordan Larsen,parkeralbert@example.org,3168629785,PURE MATHEMATICS,Kenyatta University,2026-05-12,Selected
50,Alyssa Lopez,josephleblanc@example.com,464.322.2367x1639,webdev,University of Nairobi,13/05/2026,SELECTED
51,Rebecca Welch,joe66@example.org,828-447-9389,APPLIED Statistics,Maseno University,2026-05-12,Selected
52,Kenneth Horne,lbrown@example.com,(918)615-3961x531,web development,Moi University,2026-05-12,Selected
53,Kimberly Cooper,nichole56@example.net,2849912220,web development,,13/05/2026,SELECTED
54,Donna Jones,fhill@example.com,447-324-2782,Applied Statistics,University of Nairobi,2026-05-12,Rejected
55,Leah Harmon MD,mariahayes@example.com,780-451-7979x8603,Applied Statistics,Egerton University,2026-05-12,
56,Tara Mendoza,aclark@example.net,7882565111,Web development,Moi University,2026-05-12,
57,Meredith Swanson,zachary87@example.net,001-264-687-0831x26655,WEB DEV,Maseno University,13/05/2026,Rejected
58,Patrick Thomas,nicholas09@example.com,+1-546-716-9496x14534,web development,Moi University,2026-05-12,Under Review
59,James Wilson,blopez@example.org,688.510.8074,PURE MATHEMATICS,,13/05/2026,Selected
60,Brent Brown,bennettcody@example.org,529-373-2939x26992,web development,Egerton University,2026-05-12,SELECTED
61,Samantha Davis,ismith@example.net,001-377-904-0367x0576,WEB DEV,Maseno University,13/05/2026,Rejected
62,Christopher Thompson,susan96@example.net,5509006994,PURE MATHEMATICS,,2026-05-12,Rejected
63,Susan Frye,fredericksuarez@example.net,001-354-341-1048x3050,APPLIED Statistics,JKUAT University,2026-05-12,Rejected
64,Michael Smith,emilyturner@example.com,001-540-642-9362x6497,APPLIED Statistics,Maseno University,13/05/2026,Selected
65,Kimberly Lopez,carpentergary@example.org,001-916-882-3743x378,Applied Statistics,Maseno University,2026-05-12,Rejected
66,Leah Patterson,leepayne@example.net,(906)411-2344x548,webdev,,2026-05-12,selected
67,Amanda Andrews,molly98@example.org,467-559-9871,Web development,Kenyatta University,13/05/2026,SELECTED
68,Dr. Steven Hoover,jonessamantha@example.org,(649)530-9003x733,COMPUTER sci,JKUAT University,13/05/2026,UNDER REVIEW
69,Laurie Torres,matthew44@example.net,001-770-440-2512x081,COMPUTER sci,Egerton University,13/05/2026,Selected
70,Melissa Murray,daniel48@example.net,207.911.4023x837,web development,JKUAT University,13/05/2026,UNDER REVIEW
71,Adam Stuart,rileymichael@example.net,934.858.4637,WEB DEV,,2026-05-12,selected
72,Samantha Davis,lsanchez@example.net,203.865.7548,web development,,13/05/2026,Rejected
73,Cynthia Garcia,michaelhill@example.org,704.383.6648,WEB DEV,Maseno University,13/05/2026,Under Review
74,Robert Curry,justinpope@example.net,001-301-364-9705x9401,Data SCIENCE,University of Nairobi,2026-05-12,selected
75,Carl Lewis,kathrynwarner@example.net,382.244.0997,web development,,13/05/2026,Selected
76,Joy Mack,jillian93@example.com,382-690-2761,PURE MATHEMATICS,Maseno University,2026-05-12,SELECTED
77,Darrell Douglas,torressteven@example.com,523.858.3404x6314,Web development,Moi University,13/05/2026,Rejected
78,Ryan Reeves,callahanamy@example.net,+1-570-500-4775,web development,,13/05/2026,Selected
79,Jennifer Smith,mmorgan@example.org,(885)673-0970x289,web development,Kenyatta University,13/05/2026,
80,Mike Duarte,seanhenson@example.org,923-836-1568x47480,Data SCIENCE,Kenyatta University,2026-05-12,UNDER REVIEW
81,Eric Medina,jorge95@example.org,225-281-8652,Data SCIENCE,,2026-05-12,SELECTED
82,Tony Gray,nfuentes@example.com,+1-985-359-8576x2411,Applied Statistics,,13/05/2026,
83,James Jones,eric85@example.com,6202538305,Web development,JKUAT University,13/05/2026,selected
84,Jeremy Montgomery,brownmelissa@example.net,001-924-517-8806x5077,web dev,Maseno University,13/05/2026,SELECTED
85,Adam Brown,agriffin@example.org,001-821-768-3342,APPLIED Statistics,Egerton University,13/05/2026,UNDER REVIEW
86,Eric Melton,cynthialarson@example.org,7008283270,Web development,University of Nairobi,13/05/2026,SELECTED
87,Stephanie Chang,alex30@example.org,884-239-6017x1272,Data SCIENCE,Maseno University,13/05/2026,UNDER REVIEW
88,Carrie Cannon PhD,christopherjuarez@example.com,838.798.2479,Applied Statistics,University of Nairobi,2026-05-12,Rejected
89,Melanie Paul,michelefrazier@example.net,(807)793-2617x9024,web development,,13/05/2026,Selected
90,Rebecca Bowen,cruzcaitlin@example.com,(817)526-4447,web development,Kenyatta University,13/05/2026,Under Review
91,Angelica Atkins,iparsons@example.org,(654)925-3428x525,web dev,Moi University,13/05/2026,UNDER REVIEW
92,Gabrielle Burgess,crossmadeline@example.com,(900)799-9446,WEB DEV,Moi University,13/05/2026,Rejected
93,Johnny Stephenson,sarahbarrera@example.net,991.881.7618,web development,JKUAT University,2026-05-12,SELECTED
94,Shawn Rush,joneskevin@example.com,+1-807-685-3378,web dev,,13/05/2026,selected
95,Morgan Decker,hchen@example.net,+1-562-879-4030x9956,APPLIED Statistics,,2026-05-12,Rejected
96,Daniel Carr,eric00@example.org,690-860-9789,web development,,13/05/2026,Rejected
97,Christopher Hernandez,curtischad@example.org,317.565.2152x716,Applied Statistics,,2026-05-12,Under Review
98,Susan Lee,NaN,805-508-9632x921,Data SCIENCE,JKUAT University,2026-05-12,Selected
99,Rebecca Fisher,NaN,628-810-3131x80133,PURE MATHEMATICS,University of Nairobi,2026-05-12,Rejected
100,Valerie Miller,melanie29@example.org,809-313-8551x7574,webdev,,2026-05-12,Under Review
101,Robert Johnston,briansmith@example.org,568.788.3065x7244,Web development,Moi University,2026-05-12,
102,Breanna Solis,christopher86@example.net,001-812-435-4182x708,web dev,Egerton University,13/05/2026,SELECTED

# *I created the applicants dataset with 103 rows and 7 columns. Some of the rows contained missing values, duplicates, bad formatting and blank cells so that my cleaning process has the real work to do.*

## **Step 3: First Look - Understand Before You Clean.**
Never start cleaning blindly. First, explore what you are working with:

In [111]:
#HOw many rows and columns?
df.shape #The dataframe has 103 rows and 7 columns.

(103, 7)

In [112]:
#preview the first 5 rows
df.head()#The first 5 rows were clearly displayed.

,Applicant_Name,Email,Phone,Domain_Applied,University_Name,Application_date,Status
0,Valerie Miller,melanie29@example.org,809-313-8551x7574,webdev,,2026-05-12,Under Review
1,Robert Johnston,briansmith@example.org,568.788.3065x7244,Web development,Moi University,2026-05-12,
2,Breanna Solis,christopher86@example.net,001-812-435-4182x708,web dev,Egerton University,13/05/2026,SELECTED
3,Dawn Kim,kristen00@example.com,976.444.1756x4317,webdev,Egerton University,2026-05-12,UNDER REVIEW
4,Derrick Moore,kolson@example.net,5909238996,COMPUTER sci,Maseno University,2026-05-12,Selected

In [113]:
#data types + non-null counts per column
df.info()# The dataframe contained  integers and string variables. Applicant_ID was the only integer variable.

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant_Name    100 non-null    str
 1   Email             101 non-null    str
 2   Phone             103 non-null    str
 3   Domain_Applied    103 non-null    str
 4   University_Name   102 non-null    str
 5   Application_date  103 non-null    str
 6   Status            103 non-null    str
dtypes: str(7)
memory usage: 15.2 KB

In [114]:
#exact count of missing values per count
df.isnull().sum()

Applicant_Name      3
Email               2
Phone               0
Domain_Applied      0
University_Name     1
Application_date    0
Status              0
dtype: int64

Applicant_Name contained 3 missing values, Email contained 2 while University_Name columns contained 1 missing value. I filled the University_Name column with "Not_Specified" 

since applicants could be contcted through phone numbers provided.I filled the missing emails with not_provided@gmail.com.  
    
Since I wanted to maintain the other sections.

In [115]:
#How many exact duplicate rows exist?
df.duplicated().sum()

np.int64(3)

There were 3 exact duplicates in the original dataset

In [116]:
#How many near duplicates exist?
df.duplicated(subset = "Email").sum

<bound method Series.sum of 0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99      True
100     True
101     True
102     True
dtype: bool>

## Checking for blanks column by column

In [117]:
##Checking for blanks 
(df["Applicant_Name"] == "").sum().sum() #There were no blanks

np.int64(0)

In [118]:
(df["Email"] == "").sum().sum() #There were no blanks

np.int64(0)

In [119]:
(df["Phone"] == "").sum().sum() #There were no blanks

np.int64(0)

In [120]:
(df["Domain_Applied"] == "").sum().sum() #There were no blanks

np.int64(0)

In [121]:
(df["University_Name"] == "").sum().sum() #There were 27 blanks

np.int64(27)

In [122]:
(df["Application_date"] == "").sum().sum() #There were no blanks

np.int64(0)

In [153]:
(df["Status"] == "").sum().sum() #There were 9 blanks

np.int64(0)

There were 27 blanks in the University_Name and 9 in Status  column.

## **Step 4: Handle Blanks and Missing Values (Column by Column, With Justifiaction)**

In [124]:
#Removing blanks
df["University_Name"] = df["University_Name"] .replace("", "Not provided")
df["Status"] = df["Status"] .replace("", "Under Review")

This section removes both blanks and missing values in the University_Name and Status columns

In [125]:
#Confirm if the University_Name blanks have been removed
(df["University_Name"] == "").sum().sum()

np.int64(0)

In [126]:
#Confirm if the Statuses blanks have been removed
(df["Status"] == "").sum().sum()

np.int64(0)

In [127]:
#Applicant_Name Missing?This is critical identifying information- a row without a name is not useful.
#Consider dropping these rows.
df = df.dropna(subset = ['Applicant_Name'])

A row without an applicant name is not usefull. So I dropped the rows with missing Applicant_name.

In [128]:
#Email missing?Also fairly critical
df['Email'] = df['Email'].fillna('Not_provided@gmail.com')

I filled the missing email with "Not_provided@gmail.com". This is because the row contains other important vaues required in data analysis.

In [129]:
#University_Name Missing?
df['University_Name'] = df['University_Name'].fillna('Not Specified')

I filled missing University_Name with "Not Specified" instead of dropping, since it is not essentaial in determing application status.

## **Step 5: Checking and Remove Duplicate Applicants**

In [130]:
#Check exact duplicates first
df.duplicated().sum()

np.int64(3)

There were 3 exact duplicates in the dataset

In [131]:
#Remove Exact duplicate rows
df = df.drop_duplicates()

In [132]:
#Check for near duplicates too
#Check for for duplicate applications by the same email, keeping only the first entry.
df = df.drop_duplicates(subset = ['Email'], keep = 'first')

I checked the near duplicates by email because in this dataset, emails will act as unique identifiers.

In [133]:
df.info()

<class 'pandas.DataFrame'>
Index: 96 entries, 0 to 98
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant_Name    96 non-null     str
 1   Email             96 non-null     str
 2   Phone             96 non-null     str
 3   Domain_Applied    96 non-null     str
 4   University_Name   96 non-null     str
 5   Application_date  96 non-null     str
 6   Status            96 non-null     str
dtypes: str(7)
memory usage: 15.3 KB

The dataset consisted of 7 string variables.

## **Step 6: Standardize Text Fields**

### (i) Standardizing the Domain_Applied Column

In [134]:
df['Domain_Applied'].unique()# To confirm the domains in the original dataset

<ArrowStringArray>
[            'webdev',    'Web development',            'web dev',
       'COMPUTER sci',    'web development',  ' web development ',
   'PURE MATHEMATICS',            'WEB DEV', 'Applied Statistics',
       'Data SCIENCE', 'APPLIED Statistics']
Length: 11, dtype: str

There were 11 Domain_Applied before standardization

In [135]:
domain_mapping = {
    'web dev' : 'Web Development',
    'webdev' : 'Web Development',
    'web development' : 'Web Development',
    'WEB DEV' : 'Web Development',
    'Web development' : 'Web Development', 
    ' web development ' : 'Web Development', #Removing the white space
    'Web development' : 'Web Development',
    'Applied Statistics' : 'Applied Statistics',
    'APPLIED Statistics' : 'Applied Statistics',
    'Data SCIENCE' : 'Data Science',
    'COMPUTER sci' : 'Computer Science',
    'PURE MATHEMATICS' : 'Pure Mathematics',
}
df['Domain_Applied'] = df['Domain_Applied'].map(domain_mapping)

In [136]:
df['Domain_Applied'].unique()# To confirm the domains in the dataset after standardization

<ArrowStringArray>
[   'Web Development',   'Computer Science',   'Pure Mathematics',
 'Applied Statistics',       'Data Science']
Length: 5, dtype: str

There were 5 domains applied after standardization, that is 'Web Development', Pure Mathematics, Computer Science and 'Applied Statistics' and Data Science.

### (ii) Standardizing the Status Column

In [137]:
df['Status'].unique()#Checking the contents of the status column

<ArrowStringArray>
['Under Review', 'SELECTED', 'UNDER REVIEW', 'Selected', 'Rejected',
 'selected']
Length: 6, dtype: str

The Status Column comprised 6 inconsistent values: 'selected', 'Selected', 'SELECTED', 'Under Review', 'UNDER REVIEW' and 'Rejected'.

In [138]:
#Ensure that all the values in Status column become one consistent value. 
df['Status'] = df['Status'].str.strip().str.title()

In [139]:
df['Status'].unique() #Checking the values in the Status column are consistent

<ArrowStringArray>
['Under Review', 'Selected', 'Rejected']
Length: 3, dtype: str

The standardized Status column has 3 consistent values: 'Selected', 'Under Review' and 'Rejected'.

## **Step 7: Fix Data Types (Especially Dates and Phone Numbers)**

In [140]:
#Fixing the date column
df['Application_date'] = pd.to_datetime(df['Application_date'], errors = 'coerce')

In [141]:
df['Application_date'].isnull().sum()

np.int64(46)

This created 46 missing dates

In [142]:
#Fixing this
#Convert all the valid dates into Pandas datime format
df["Application_date"] = pd.to_datetime(
    df["Application_date"],
    format = "mixed", #This al;ows Pandas to recognise different formats
    dayfirst = True,
    errors = "coerce" # Converts invalid dates into missing values
)

I replaced the missing dates 2026-05-13

In [143]:
df["Application_date"] = df["Application_date"].fillna(pd.to_datetime("2026-05-13"))

I displayed the dates consistently as YYYY=MM-DD

In [144]:
#Fixing the Phone Column

I removed dashes and spaces to create a consistent format

In [145]:
df['Phone'] = df['Phone'].str.replace("-", '', regex = False).str.replace(' ', '', regex = False)

In [146]:
df.info()

<class 'pandas.DataFrame'>
Index: 96 entries, 0 to 98
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant_Name    96 non-null     str
 1   Email             96 non-null     str
 2   Phone             96 non-null     str
 3   Domain_Applied    96 non-null     str
 4   University_Name   96 non-null     str
 5   Application_date  96 non-null     datetime64[us]
 6   Status            96 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 14.5 KB

In [147]:
#HOw many rows and columns?
df.shape #The new dataframe has 96 rows and 7 columns.

(96, 7)

The new dataframe has 96 rows and 7 columns

In [148]:
#exact count of missing values per count in the new dataframe
df.isnull().sum()

Applicant_Name      0
Email               0
Phone               0
Domain_Applied      0
University_Name     0
Application_date    0
Status              0
dtype: int64

The new dataframe has no missing values

In [149]:
#How many exact duplicate rows exist?
df.duplicated().sum()

np.int64(0)

There were no duplicates after cleaning.

In [151]:
display(df)

,Applicant_Name,Email,Phone,Domain_Applied,University_Name,Application_date,Status
0,Valerie Miller,melanie29@example.org,8093138551x7574,Web Development,Not provided,2026-05-12,Under Review
1,Robert Johnston,briansmith@example.org,568.788.3065x7244,Web Development,Moi University,2026-05-12,Under Review
2,Breanna Solis,christopher86@example.net,0018124354182x708,Web Development,Egerton University,2026-05-13,Selected
3,Dawn Kim,kristen00@example.com,976.444.1756x4317,Web Development,Egerton University,2026-05-12,Under Review
4,Derrick Moore,kolson@example.net,5909238996,Computer Science,Maseno University,2026-05-12,Selected
8,Jose Wells,donnaobrien@example.org,8907345073,Web Development,Not provided,2026-05-12,Under Review
9,Lucas Odonnell,fishermichael@example.org,3786250726,Web Development,Moi University,2026-05-13,Rejected
10,Ian Hoffman,atran@example.com,9598907482,Pure Mathematics,University of Nairobi,2026-05-12,Under Review
11,Mary Lee,amyharvey@example.org,9133507350,Web Development,JKUAT University,2026-05-12,Selected
12,Jamie Andrews,myersjohn@example.net,990.608.2287x5855,Web Development,Not provided,2026-05-13,Selected
13,Benjamin Villa,cassandra07@example.com,0017563642724x3188,Pure Mathematics,Kenyatta University,2026-05-12,Selected
14,Ashley Mora,stanleyashley@example.com,212.526.8342x12423,Web Development,JKUAT University,2026-05-12,Selected
15,Susan Patel,jhunt@example.org,0015454839515x09972,Web Development,JKUAT University,2026-05-12,Selected
16,Melissa Hall,jameshobbs@example.org,+17506908509x55260,Web Development,Not provided,2026-05-13,Under Review
17,Jacob Banks,nbell@example.com,(895)3932376x88308,Applied Statistics,Not provided,2026-05-12,Under Review
18,Brandon Cox,xschmidt@example.com,8806548810,Web Development,Kenyatta University,2026-05-13,Selected
19,Carolyn Wilson,sandragallegos@example.com,(481)6088078x6328,Web Development,University of Nairobi,2026-05-13,Under Review
20,Edward Taylor,shawnmunoz@example.org,9763205299,Web Development,Egerton University,2026-05-12,Selected
21,Rick Wiggins,ginareed@example.net,+19894528844x510,Computer Science,Not Specified,2026-05-13,Rejected
22,Sandra Flores,fcarroll@example.com,+18194074519x86541,Web Development,JKUAT University,2026-05-13,Selected
23,Patricia Graves,russellrichard@example.org,(834)2760411x0843,Data Science,Not provided,2026-05-13,Rejected
24,Timothy Smith,kcarpenter@example.org,7882160493,Pure Mathematics,Egerton University,2026-05-12,Under Review
25,Alicia Austin,mitchellelizabeth@example.net,8167379623,Applied Statistics,University of Nairobi,2026-05-13,Under Review
26,David Ramirez,randall53@example.com,8207116963,Web Development,Egerton University,2026-05-13,Under Review
27,Larry Walker,amandasimmons@example.net,835.620.2605x0890,Web Development,Egerton University,2026-05-12,Selected
28,Cameron Harris,bartondaniel@example.net,+13394240646x5396,Data Science,Egerton University,2026-05-12,Under Review
29,Edward Bowen,laurenhernandez@example.org,4348235377,Pure Mathematics,Egerton University,2026-05-13,Under Review
30,Jean Stephens,jason32@example.org,9083282783,Web Development,University of Nairobi,2026-05-13,Selected
31,Stephanie Petersen,yaustin@example.net,0012475948316,Web Development,Kenyatta University,2026-05-12,Under Review
32,Michael Lopez,allisonwest@example.net,(976)3766543,Computer Science,University of Nairobi,2026-05-12,Rejected
33,Teresa Garcia,zrodriguez@example.org,968.623.2869x93308,Web Development,Egerton University,2026-05-12,Selected
34,Regina Orozco,thomas38@example.net,0016602272537x182,Web Development,JKUAT University,2026-05-13,Selected
35,Ryan Thompson,dana88@example.org,0013686425345x32683,Web Development,Moi University,2026-05-12,Rejected
36,Jennifer Adkins,creid@example.org,(222)6139833,Computer Science,University of Nairobi,2026-05-12,Selected
37,Mr. Brian Schaefer,jonessamantha@example.net,9675916996,Applied Statistics,Not provided,2026-05-12,Under Review
38,Clifford Rasmussen,martinezjoshua@example.net,(836)2807639x00121,Web Development,Kenyatta University,2026-05-12,Under Review
39,Patrick Mcdonald,ksantos@example.org,+18455797771,Web Development,JKUAT University,2026-05-13,Selected
40,Veronica Smith,anthonylee@example.org,(696)6051853,Applied Statistics,Not provided,2026-05-12,Selected
41,Jessica Perez,kelly21@example.com,2644767258x260,Web Development,University of Nairobi,2026-05-12,Selected
42,Jessica Dodson,jonathanmaddox@example.com,9982130656,Applied Statistics,Kenyatta University,2026-05-13,Selected
43,Judith Knapp,troyshelton@example.org,6896680768,Applied Statistics,Not provided,2026-05-12,Under Review
44,Lauren Blackburn,melissaford@example.com,7922136716x4655,Applied Statistics,Maseno University,2026-05-12,Selected
45,George Hall,lpalmer@example.org,763.856.8937,Computer Science,University of Nairobi,2026-05-12,Selected
46,Dustin Rodriguez,jamie17@example.net,+12446922780,Web Development,Moi University,2026-05-13,Selected
47,Kathleen Doyle,daniel20@example.com,+19195268291x8264,Web Development,Not provided,2026-05-13,Selected
48,Stephanie Webster,hroberts@example.com,(411)4312867x9531,Applied Statistics,Kenyatta University,2026-05-12,Selected
49,Jordan Larsen,parkeralbert@example.org,3168629785,Pure Mathematics,Kenyatta University,2026-05-12,Selected
50,Alyssa Lopez,josephleblanc@example.com,464.322.2367x1639,Web Development,University of Nairobi,2026-05-13,Selected
51,Rebecca Welch,joe66@example.org,8284479389,Applied Statistics,Maseno University,2026-05-12,Selected
52,Kenneth Horne,lbrown@example.com,(918)6153961x531,Web Development,Moi University,2026-05-12,Selected
53,Kimberly Cooper,nichole56@example.net,2849912220,Web Development,Not provided,2026-05-13,Selected
54,Donna Jones,fhill@example.com,4473242782,Applied Statistics,University of Nairobi,2026-05-12,Rejected
55,Leah Harmon MD,mariahayes@example.com,7804517979x8603,Applied Statistics,Egerton University,2026-05-12,Under Review
56,Tara Mendoza,aclark@example.net,7882565111,Web Development,Moi University,2026-05-12,Under Review
57,Meredith Swanson,zachary87@example.net,0012646870831x26655,Web Development,Maseno University,2026-05-13,Rejected
58,Patrick Thomas,nicholas09@example.com,+15467169496x14534,Web Development,Moi University,2026-05-12,Under Review
59,James Wilson,blopez@example.org,688.510.8074,Pure Mathematics,Not provided,2026-05-13,Selected
60,Brent Brown,bennettcody@example.org,5293732939x26992,Web Development,Egerton University,2026-05-12,Selected
61,Samantha Davis,ismith@example.net,0013779040367x0576,Web Development,Maseno University,2026-05-13,Rejected
62,Christopher Thompson,susan96@example.net,5509006994,Pure Mathematics,Not provided,2026-05-12,Rejected
63,Susan Frye,fredericksuarez@example.net,0013543411048x3050,Applied Statistics,JKUAT University,2026-05-12,Rejected
64,Michael Smith,emilyturner@example.com,0015406429362x6497,Applied Statistics,Maseno University,2026-05-13,Selected
65,Kimberly Lopez,carpentergary@example.org,0019168823743x378,Applied Statistics,Maseno University,2026-05-12,Rejected
66,Leah Patterson,leepayne@example.net,(906)4112344x548,Web Development,Not provided,2026-05-12,Selected
67,Amanda Andrews,molly98@example.org,4675599871,Web Development,Kenyatta University,2026-05-13,Selected
68,Dr. Steven Hoover,jonessamantha@example.org,(649)5309003x733,Computer Science,JKUAT University,2026-05-13,Under Review
69,Laurie Torres,matthew44@example.net,0017704402512x081,Computer Science,Egerton University,2026-05-13,Selected
70,Melissa Murray,daniel48@example.net,207.911.4023x837,Web Development,JKUAT University,2026-05-13,Under Review
71,Adam Stuart,rileymichael@example.net,934.858.4637,Web Development,Not provided,2026-05-12,Selected
72,Samantha Davis,lsanchez@example.net,203.865.7548,Web Development,Not provided,2026-05-13,Rejected
73,Cynthia Garcia,michaelhill@example.org,704.383.6648,Web Development,Maseno University,2026-05-13,Under Review
74,Robert Curry,justinpope@example.net,0013013649705x9401,Data Science,University of Nairobi,2026-05-12,Selected
75,Carl Lewis,kathrynwarner@example.net,382.244.0997,Web Development,Not provided,2026-05-13,Selected
76,Joy Mack,jillian93@example.com,3826902761,Pure Mathematics,Maseno University,2026-05-12,Selected
77,Darrell Douglas,torressteven@example.com,523.858.3404x6314,Web Development,Moi University,2026-05-13,Rejected
78,Ryan Reeves,callahanamy@example.net,+15705004775,Web Development,Not provided,2026-05-13,Selected
79,Jennifer Smith,mmorgan@example.org,(885)6730970x289,Web Development,Kenyatta University,2026-05-13,Under Review
80,Mike Duarte,seanhenson@example.org,9238361568x47480,Data Science,Kenyatta University,2026-05-12,Under Review
81,Eric Medina,jorge95@example.org,2252818652,Data Science,Not provided,2026-05-12,Selected
82,Tony Gray,nfuentes@example.com,+19853598576x2411,Applied Statistics,Not provided,2026-05-13,Under Review
83,James Jones,eric85@example.com,6202538305,Web Development,JKUAT University,2026-05-13,Selected
84,Jeremy Montgomery,brownmelissa@example.net,0019245178806x5077,Web Development,Maseno University,2026-05-13,Selected
85,Adam Brown,agriffin@example.org,0018217683342,Applied Statistics,Egerton University,2026-05-13,Under Review
86,Eric Melton,cynthialarson@example.org,7008283270,Web Development,University of Nairobi,2026-05-13,Selected
87,Stephanie Chang,alex30@example.org,8842396017x1272,Data Science,Maseno University,2026-05-13,Under Review
88,Carrie Cannon PhD,christopherjuarez@example.com,838.798.2479,Applied Statistics,University of Nairobi,2026-05-12,Rejected
89,Melanie Paul,michelefrazier@example.net,(807)7932617x9024,Web Development,Not provided,2026-05-13,Selected
90,Rebecca Bowen,cruzcaitlin@example.com,(817)5264447,Web Development,Kenyatta University,2026-05-13,Under Review
91,Angelica Atkins,iparsons@example.org,(654)9253428x525,Web Development,Moi University,2026-05-13,Under Review
92,Gabrielle Burgess,crossmadeline@example.com,(900)7999446,Web Development,Moi University,2026-05-13,Rejected
93,Johnny Stephenson,sarahbarrera@example.net,991.881.7618,Web Development,JKUAT University,2026-05-12,Selected
94,Shawn Rush,joneskevin@example.com,+18076853378,Web Development,Not provided,2026-05-13,Selected
95,Morgan Decker,hchen@example.net,+15628794030x9956,Applied Statistics,Not provided,2026-05-12,Rejected
96,Daniel Carr,eric00@example.org,6908609789,Web Development,Not provided,2026-05-13,Rejected
97,Christopher Hernandez,curtischad@example.org,317.565.2152x716,Applied Statistics,Not provided,2026-05-12,Under Review
98,Susan Lee,Not_provided@gmail.com,8055089632x921,Data Science,JKUAT University,2026-05-12,Selected

## **Step 8: Write the Data Quality Summary**

# **Data Quality Summary**

#### ***Starting dataset: 103 rows, 7 columns***

#issues found:
- 3 mising value in Applicat_Name, 2 missing values in Email, 1 in University#Done
- 3 exact duplicate rows , plus 0 additional duplicate applications identified by matching Email.#Done
- Domain_Applied had 11 different spelling and casing variations for only 5 real domains#Done
- Application_Date was stored as text , not as an actual date type#Done
- Phone numbers contained inconsistent  dash/space formatting.#Done
- University_Name had 27 blanks while Status had 9 blanks.
  
#Actions taken:
- Dropped 3 rows with missing Applicant_Name (Unusual without identification)
- Filled missing Email with "Not_provided@gmail.com".
- Filled missing University with "Not Specified" (non-critical field)
- Filled missing Status with "Under Review"
- Filling blank statatuses with "Under Review" while the University_Name blanks were filed with "Not provided".
- Removed 3 duplicate rows total (3 exact, 0 by matchingEmail)#Done
- Standardized  all Domain_Applied values into 5 consistent categories.
- Converted Application_Date for proper datetime format
- Cleaned Phone number formatting for consistency
- Filling the missing Email with "Not_provided@gmail.com" resulted in near duplicates. So 1 row was dropped.

Final dataset: 96 rows, 7 columns, no missing values in critical fields, no duplicates, consistent formatting throughout.

# **Step 9: Exporting the Cleaned Data**

In [154]:
df.to_csv('applicants_cleaned.csv', index = False)